// client/src/app/zoom-levels/sector-view/sector-view.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-sector-view',
  templateUrl: './sector-view.component.html',
  styleUrls: ['./sector-view.component.css']
})
export class SectorViewComponent implements OnInit {

  constructor() { }
  sector = [
      {
        systemStar: 'Red-Supergiant',
        systemName: 'A64122',
        systemPlanets: [
          'Gas', 'Gas',
          'Frozen', 'Frozen',
          'Lava', 'Frozen',
          'Gas', 'Frozen'
        ],
        distanceFromTop: 400,
        distanceFromLeft: 360
      },
      {
        systemStar: 'Blue-Giant',
        systemName: 'A49627',
        systemPlanets: ['Lava'],
        distanceFromTop: 463,
        distanceFromLeft: 163
      },
      {
        systemStar: 'Red-Giant',
        systemName: 'A50889',
        systemPlanets: ['Rocky', 'Frozen'],
        distanceFromTop: 71,
        distanceFromLeft: 434
      },
      {
        systemStar: 'Yellow-Dwarf',
        systemName: 'A60984',
        systemPlanets: ['Frozen', 'Temperate', 'Rocky', 'Lava', 'Ocean'],
        distanceFromTop: 138,
        distanceFromLeft: 638
      },
      {
        systemStar: 'Red-Supergiant',
        systemName: 'A35421',
        systemPlanets: ['Rocky', 'Ocean', 'Temperate', 'Gas', 'Lava'],
        distanceFromTop: 13,
        distanceFromLeft: 899
      },
      {
        systemStar: 'Red-Dwarf',
        systemName: 'A48843',
        systemPlanets: ['Rocky', 'Gas'],
        distanceFromTop: 856,
        distanceFromLeft: 523
      },
      {
        systemStar: 'Yellow-Dwarf',
        systemName: 'A63396',
        systemPlanets: ['Temperate', 'Gas', 'Lava', 'Gas', 'Rocky'],
        distanceFromTop: 810,
        distanceFromLeft: 250
      },
      {
        systemStar: 'Blue-Giant',
        systemName: 'A82856',
        systemPlanets: ['Rocky'],
        distanceFromTop: 874,
        distanceFromLeft: 472
      },
      {
        systemStar: 'Red-Giant',
        systemName: 'A38881',
        systemPlanets: [],
        distanceFromTop: 742,
        distanceFromLeft: 556
      },
  ];
  sectorName = "Sector 1"
  ngOnInit() {
  }

}

<h3 class="sector-name">{{sectorName}}</h3>
<tbody>
   
    
    <div *ngFor="let star of sector">
<div><a routerLink={{star.systemName}}>{{star.systemName}}</a></div>
<p>top:{{star.distanceFromTop}}</p>
<p>left:{{star.distanceFromLeft}}</p>
    </div>
  </tbody>

// src/views/sector-view.tsx
import React, { useState } from "react";
import { Link } from "react-router-dom";



export const SectorView = () => {
  const [sector, setSector] = React.useState<
    Array<{
      systemName: String,
      systemStar: String,
      systemPlanets: Array<String>,
      distanceFromTop: Number,
      distanceFromLeft: Number
    }>
  >([
    {
      systemStar: 'Red-Supergiant',
      systemName: 'A64122',
      systemPlanets: [
        'Gas', 'Gas',
        'Frozen', 'Frozen',
        'Lava', 'Frozen',
        'Gas', 'Frozen'
      ],
      distanceFromTop: 400,
      distanceFromLeft: 360
    },
    {
      systemStar: 'Red-Supergiant',
      systemName: 'A64122',
      systemPlanets: [
        'Gas', 'Gas',
        'Frozen', 'Frozen',
        'Lava', 'Frozen',
        'Gas', 'Frozen'
      ],
      distanceFromTop: 400,
      distanceFromLeft: 360
    },
    {
      systemStar: 'Blue-Giant',
      systemName: 'A49627',
      systemPlanets: ['Lava'],
      distanceFromTop: 463,
      distanceFromLeft: 163
    },
    {
      systemStar: 'Red-Giant',
      systemName: 'A50889',
      systemPlanets: ['Rocky', 'Frozen'],
      distanceFromTop: 71,
      distanceFromLeft: 434
    },
    {
      systemStar: 'Yellow-Dwarf',
      systemName: 'A60984',
      systemPlanets: ['Frozen', 'Temperate', 'Rocky', 'Lava', 'Ocean'],
      distanceFromTop: 138,
      distanceFromLeft: 638
    },
    {
      systemStar: 'Red-Supergiant',
      systemName: 'A35421',
      systemPlanets: ['Rocky', 'Ocean', 'Temperate', 'Gas', 'Lava'],
      distanceFromTop: 13,
      distanceFromLeft: 899
    },
    {
      systemStar: 'Red-Dwarf',
      systemName: 'A48843',
      systemPlanets: ['Rocky', 'Gas'],
      distanceFromTop: 856,
      distanceFromLeft: 523
    },
    {
      systemStar: 'Yellow-Dwarf',
      systemName: 'A63396',
      systemPlanets: ['Temperate', 'Gas', 'Lava', 'Gas', 'Rocky'],
      distanceFromTop: 810,
      distanceFromLeft: 250
    },
    {
      systemStar: 'Blue-Giant',
      systemName: 'A82856',
      systemPlanets: ['Rocky'],
      distanceFromTop: 874,
      distanceFromLeft: 472
    },
    {
      systemStar: 'Red-Giant',
      systemName: 'A38881',
      systemPlanets: [],
      distanceFromTop: 742,
      distanceFromLeft: 556
    },
  ])

  {
    return (
      <div>astast
      {sector.map((sector) => {
        return (
          <Link to={`/system/${sector.systemName}`}><p>{sector.systemName}</p></Link>
        )
      })}
      </div>
    )
    
  }
}
